### ISSUE TITLE
Need help for downloaded data

### ISSUE THREAD

**Issue by hdp2101** [nandp1/nser#1]
Hello

I successfully downloaded bhavcopy data, but can you guide me this file is located?

Please see the output

> library(nser)
> # Download Bhavcopy of 1st July 2021
> report1 = bhav("01072021")
trying URL 'https://archives.nseindia.com/content/historical/EQUITIES/2021/JUL/cm01JUL2021bhav.csv.zip'
Content type 'application/zip' length 76717 bytes (74 KB)
downloaded 74 KB

> library(nser)
> report = fobhav("01072021")
trying URL 'https://archives.nseindia.com/content/historical/DERIVATIVES/2021/JUL/fo01JUL2021bhav.csv.zip'
Content type 'application/zip' length 593613 bytes (579 KB)
downloaded 579 KB

> head(report)
  INSTRUMENT    SYMBOL   EXPIRY_DT STRIKE_PR OPTION_TYP     OPEN     HIGH
1     FUTIDX BANKNIFTY 29-Jul-2021         0         XX 34975.75 35086.35
2     FUTIDX BANKNIFTY 26-Aug-2021         0         XX 35426.30 35426.30
3     FUTIDX BANKNIFTY 30-Sep-2021         0         XX 35303.05 35358.20
4     FUTIDX  FINNIFTY 01-Jul-2021         0         XX 16480.00 16480.00
5     FUTIDX  FINNIFTY 08-Jul-2021         0         XX 16435.00 16435.00
6     FUTIDX  FINNIFTY 15-Jul-2021         0         XX     0.00     0.00
       LOW    CLOSE SETTLE_PR CONTRACTS VAL_INLAKH OPEN_INT CHG_IN_OI
1 34810.85 34853.05  34853.05    105417  920286.40  2113400    -91225
2 34973.45 35004.70  35004.70      2041   17894.82    79450      3850
3 35128.85 35159.30  35159.30       264    2324.22    10300       425
4 16368.50 16373.10  16376.85       112     735.46      600      -720
5 16415.00 16415.00  16388.35         3      19.70      240       120
6     0.00 15608.35  16399.80         0       0.00        0         0
    TIMESTAMP  X
1 01-JUL-2021 NA
2 01-JUL-2021 NA
3 01-JUL-2021 NA
4 01-JUL-2021 NA
5 01-JUL-2021 NA
6 01-JUL-2021 NA
> local({fn<-choose.files(filters=Filters[c('R','txt','All'),],index=4)
+ file.show(fn,header=fn,title='')})
> 

Thank you

**Comment by nandp1** [comment]
Hi, 

The bhavcopy isn't downloaded locally on your system, it is present in a temporary folder. If you need csv or excel copy you need to export it from R. 

Sorry for delayed response.
